### ISSUE TITLE
Trouble running on visium sample

### ISSUE THREAD

**Issue by dcjones** [messcode/STAMarker#6]
I'm struggling to reproduce some results from the paper. I'm running stamarker on the human visium 151507 sample, by adapting code from the tutorial, but I end up with domains that look like this:
![image](https://user-images.githubusercontent.com/210361/226502845-4efe626f-1a47-42e9-879c-ac98cd4c7de9.png)

Do you have any advice as to what I might be doing wrong? Are there parameters that need to be different than what's shown in the example?

**Comment by messcode** [comment]
Thank you for your inquiry.  I have made the necessary code updates and included a functional example of the DLPFC dataset. Kindly refer to the link provided below to access it:

https://github.com/messcode/STAMarker/blob/main/tutorial/Human-DLPFC-10x-Visum.ipynb.

I suggest adjusting the parameter rad_cutoff in data_module.prepare_data to achieve an average number of neighbors ranging from 5 to 10.

Poor performance is possible due to the model being under-trained. Please set the training epochs of `stagate_trainer` in the `trainer.yaml` to `max_epochs: 1000` and `min_epochs`: 500 .  

Please also refer to the description of the model specification (https://github.com/messcode/STAMarker/tree/main/tutorial/README.md).

**Comment by dcjones** [comment]
I have it working now, thanks for the help!
