### ISSUE TITLE
Some doubts about the use of STAMarker code

### ISSUE THREAD

**Issue by februaryfang** [messcode/STAMarker#7]
Hello,
Thank you for the work on the STAMarker tool. I am interested in using STAMarker to analyze my own spatial data. However, while following the tutorial provided in "Mouse-cerebellum.ipynb," I have encountered several issues.
1. When replicating the steps outlined in the "Mouse-cerebellum.ipynb" tutorial, I am unable to reproduce the example results. Were there any cell filtering processes applied in the publication that might not be detailed in the tutorial? Additionally, could you specify the exact number of Spatially Variable Genes (SVGs) obtained from this analysis?
2. The literature recommends setting n_auto_encoders to 20, yet the tutorial employs a value of 5. Could you clarify how n_auto_encoders was configured in the Mouse-cerebellum study as described in the publication?
3. There appears to be an error in the command sequence within the tutorial:
`smaps = stamarker.compute_smaps(data_module, return_recon=False)
smaps_mean = np.mean(np.array(smaps), axis=0)
zsmap = stamarker._compute_smap_zscore(smaps_mean, stamarker.consensus_labels)
smaps = pd.DataFrame(smaps_mean)`
Is it necessary to compute the mean of smaps using np.mean before applying the z-score transformation via stamarker._compute_smap_zscore? My understanding is that stamarker._compute_smap_zscore should directly transform smaps into zsmap.
4. Lastly, would it be possible to provide the code for generating the following visualizations: the gene module clustering diagram, the saliency map heatmap, and the gene module heatmap?

I appreciate your assistance and look forward to your guidance.

**Comment by messcode** [comment]
Hello februaryfang,

Thank you for reaching out with your inquiry.

1. The initial version of the implementation required several hours (up to days) to calculate the consensus matrix. I have since optimized the consensus_clustering process using linear sum assignment to expedite it. However, the consensus clustering still takes over an hour to complete. The original analysis identified 508 SVGs.
2. To reduce the runtime for generating illustrations, we employed 5 autoencoders. You have the option to increase this number to 20, should you wish to do so.
3. You are indeed correct that computing zsmap is unnecessary for SVG selection, and I have made the appropriate correction. Zsmap is utilized for visualizing gene modules. For more information, please refer to the updated [Tutorial 2](https://github.com/messcode/STAMarker/blob/main/tutorial/Human-DLPFC-10x-Visum.ipynb).
4. I have included the function that I utilized in Tutorial 2 for your reference.


Thank you for your attention to these details. I hope this information is helpful to you.
